In [73]:
import pandas as pd
df = pd.read_csv('전체언론사_20200201-20200831.csv', error_bad_lines = False)
df

        Unnamed: 0   언론사                                                키워드
0                0  경향신문  신정락,선수,코로나,확진,KBO,초비상,접촉,격리,의심,선수,한화,확진,통보,매뉴얼...
1                1  경향신문  겨냥,가구,식품,식구,식탁,점령,코로나,집밥,선호,가정,늘자,생선구이,로스트치킨,주...
2                2  경향신문  사임,책임,회피,NYT,일본,교수,기고,코로나,대응,스캔들,면피,후임,총리,스가,대...
3                3  경향신문  대통령,의료,파업,정부,선택지,유감,촉구,대승,결단,문재인,대통령,집단,파업,의료계...
4                4  경향신문  관방장관,사의,전격,표명,아베,신조,일본,총리,후임,스가,요시히데,菅義偉,관방장관,...
...            ...   ...                                                ...
178609       19995   KBS  싱하이밍,신임,대사,코로나,신종,기자회견,앵커,싱하이밍,신임,주한,중국,대사,부임,...
178610       19996   KBS  자제령,중국,외출,8일,앵커,당국,중국,보건,전역,사실,중국,대상,외출,자제령,감염...
178611       19997   KBS  확진자,10명,해외,감염,추가,대책,마련,앵커,환자수,코로나바이러스,감염,확진,환자...
178612       19998   KBS  2번,환자,치료,퇴원,생활,앵커,번째,증상,국립중앙의료원,격리,열흘간,치료,재난방송...
178613       19999   KBS  번째,퇴원,완치,가능성,앵커,신종,코로,바이러스,밤사이,추가,확진,환자,소식,환자,...

[178614 rows x 3 columns]

In [74]:
del df['Unnamed: 0']

In [75]:
df

         언론사                                                키워드
0       경향신문  신정락,선수,코로나,확진,KBO,초비상,접촉,격리,의심,선수,한화,확진,통보,매뉴얼...
1       경향신문  겨냥,가구,식품,식구,식탁,점령,코로나,집밥,선호,가정,늘자,생선구이,로스트치킨,주...
2       경향신문  사임,책임,회피,NYT,일본,교수,기고,코로나,대응,스캔들,면피,후임,총리,스가,대...
3       경향신문  대통령,의료,파업,정부,선택지,유감,촉구,대승,결단,문재인,대통령,집단,파업,의료계...
4       경향신문  관방장관,사의,전격,표명,아베,신조,일본,총리,후임,스가,요시히데,菅義偉,관방장관,...
...      ...                                                ...
178609   KBS  싱하이밍,신임,대사,코로나,신종,기자회견,앵커,싱하이밍,신임,주한,중국,대사,부임,...
178610   KBS  자제령,중국,외출,8일,앵커,당국,중국,보건,전역,사실,중국,대상,외출,자제령,감염...
178611   KBS  확진자,10명,해외,감염,추가,대책,마련,앵커,환자수,코로나바이러스,감염,확진,환자...
178612   KBS  2번,환자,치료,퇴원,생활,앵커,번째,증상,국립중앙의료원,격리,열흘간,치료,재난방송...
178613   KBS  번째,퇴원,완치,가능성,앵커,신종,코로,바이러스,밤사이,추가,확진,환자,소식,환자,...

[178614 rows x 2 columns]

In [44]:
df = df.sort_values(by=['언론사'],ascending=True)
df

        Unnamed: 0    언론사                                                키워드
178613       19999    KBS  번째,퇴원,완치,가능성,앵커,신종,코로,바이러스,밤사이,추가,확진,환자,소식,환자,...
169338       10724    KBS  정점,보건,당국자,근접,트럼프,경제,정상,결정,권한,앵커,미국,연일,코로,확진자,신...
169345       10731    KBS  코리안,좀비,정찬,도전,UFC,챔피언,앵커,경기,한국,종합,격투기,대표,선수,UFC...
169346       10732    KBS  고독,부활절,두오모,희망,노래,앵커,코로나19,세계,지구촌,경험,고독,부활절,기독교...
169347       10733    KBS  세계,석학,언급,코로나19,세계,온라인,수업,재택근무,분리수거,생활,방역,생활,폭풍...
...            ...    ...                                                ...
154839       16074  헤럴드경제  코로나19,팬데믹,세계,경제,성장,0.1%,뉴욕증권거래소,트레이더,로이터,감염증,신...
154838       16073  헤럴드경제  국회,추경,심사,17일,처리,7일,국회,본회의,공직선거법,개정,법률안,선거구,획정안...
154836       16071  헤럴드경제  항공사,6월,5조,피해,사진,6일,전남,무안국제공항,대합실,항공사,직원,여행객,감염...
154852       16087  헤럴드경제  이재명,검토,종교,집회,긴급,명령,역사상,한국,종교,역사,긴급명령,경기도,전망,이재...
146304        7539  헤럴드경제  595만,전국,학생,등교,학교,집단,감염,중학교,135만,초등학교,학년,등교,시작,...

[178614 rows x 3 columns]

In [47]:
set(df['언론사'])

{'KBS',
 'MBC',
 'OBS',
 'SBS',
 'YTN',
 '경향신문',
 '국민일보',
 '내일신문',
 '동아일보',
 '매일경제',
 '머니투데이',
 '문화일보',
 '서울경제',
 '서울신문',
 '세계일보',
 '아시아경제',
 '아주경제',
 '조선일보',
 '중앙일보',
 '파이낸셜뉴스',
 '한겨레',
 '한국경제',
 '한국일보',
 '헤럴드경제'}

In [5]:
key = df['키워드']
key

178613    번째,퇴원,완치,가능성,앵커,신종,코로,바이러스,밤사이,추가,확진,환자,소식,환자,...
169338    정점,보건,당국자,근접,트럼프,경제,정상,결정,권한,앵커,미국,연일,코로,확진자,신...
169345    코리안,좀비,정찬,도전,UFC,챔피언,앵커,경기,한국,종합,격투기,대표,선수,UFC...
169346    고독,부활절,두오모,희망,노래,앵커,코로나19,세계,지구촌,경험,고독,부활절,기독교...
169347    세계,석학,언급,코로나19,세계,온라인,수업,재택근무,분리수거,생활,방역,생활,폭풍...
                                ...
154839    코로나19,팬데믹,세계,경제,성장,0.1%,뉴욕증권거래소,트레이더,로이터,감염증,신...
154838    국회,추경,심사,17일,처리,7일,국회,본회의,공직선거법,개정,법률안,선거구,획정안...
154836    항공사,6월,5조,피해,사진,6일,전남,무안국제공항,대합실,항공사,직원,여행객,감염...
154852    이재명,검토,종교,집회,긴급,명령,역사상,한국,종교,역사,긴급명령,경기도,전망,이재...
146304    595만,전국,학생,등교,학교,집단,감염,중학교,135만,초등학교,학년,등교,시작,...
Name: 키워드, Length: 178614, dtype: object

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(analyzer='word',stop_words=None,min_df=20,max_features=3000)
vectors = tfidf.fit_transform(key)
feature_names = tfidf.get_feature_names()
vectors.shape

(178614, 3000)

In [7]:
dense = vectors.todense()
denselist = dense.tolist()
df = pd.DataFrame(denselist, columns=feature_names)
df.to_csv('언론사들_tfidf.csv',encoding = 'utf-8-sig',header=True)

In [4]:
import pandas as pd
word = pd.read_csv('언론사들_tfidf.csv', index_col=None)
word

,Unnamed: 0,000만,000명,000억,10,100,1000만,1000명,100만,100명,...,휴대폰,휴식,휴업,휴원,휴직,흐름,흑인,흑자,희망,희생
0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.070783,0.0
2,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
3,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.271938,0.0
4,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178609,178609,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
178610,178610,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
178611,178611,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
178612,178612,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
178613,178613,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0

In [5]:
del word['Unnamed: 0']
word

,000만,000명,000억,10,100,1000만,1000명,100만,100명,10년,...,휴대폰,휴식,휴업,휴원,휴직,흐름,흑인,흑자,희망,희생
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.070783,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.271938,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178609,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
178610,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
178611,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
178612,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
178613,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0

In [10]:
word.describe

<bound method NDFrame.describe of         000만  000명  000억   10  100  1000만  1000명  100만  100명  10년  ...  휴대폰  \
0        0.0   0.0   0.0  0.0  0.0    0.0    0.0   0.0   0.0  0.0  ...  0.0
1        0.0   0.0   0.0  0.0  0.0    0.0    0.0   0.0   0.0  0.0  ...  0.0
2        0.0   0.0   0.0  0.0  0.0    0.0    0.0   0.0   0.0  0.0  ...  0.0
3        0.0   0.0   0.0  0.0  0.0    0.0    0.0   0.0   0.0  0.0  ...  0.0
4        0.0   0.0   0.0  0.0  0.0    0.0    0.0   0.0   0.0  0.0  ...  0.0
...      ...   ...   ...  ...  ...    ...    ...   ...   ...  ...  ...  ...
178609   0.0   0.0   0.0  0.0  0.0    0.0    0.0   0.0   0.0  0.0  ...  0.0
178610   0.0   0.0   0.0  0.0  0.0    0.0    0.0   0.0   0.0  0.0  ...  0.0
178611   0.0   0.0   0.0  0.0  0.0    0.0    0.0   0.0   0.0  0.0  ...  0.0
178612   0.0   0.0   0.0  0.0  0.0    0.0    0.0   0.0   0.0  0.0  ...  0.0
178613   0.0   0.0   0.0  0.0  0.0    0.0    0.0   0.0   0.0  0.0  ...  0.0

         휴식   휴업   휴원   휴직   흐름   흑인   흑자        희망   희생
0       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0
1       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.070783  0.0
2       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0
3       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.271938  0.0
4       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0
...     ...  ...  ...  ...  ...  ...  ...       ...  ...
178609  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0
178610  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0
178611  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0
178612  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0
178613  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0

[178614 rows x 3000 columns]>

In [11]:
w1 = word.loc[0:4551,:] #KBS
w1

,000만,000명,000억,10,100,1000만,1000명,100만,100명,10년,...,휴대폰,휴식,휴업,휴원,휴직,흐름,흑인,흑자,희망,희생
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.070783,0.000000
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.271938,0.000000
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4547,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
4548,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
4549,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.322818,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
4550,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
4551,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.093919

In [12]:
w1.columns

Index(['000만', '000명', '000억', '10', '100', '1000만', '1000명', '100만', '100명',
       '10년',
       ...
       '휴대폰', '휴식', '휴업', '휴원', '휴직', '흐름', '흑인', '흑자', '희망', '희생'],
      dtype='object', length=3000)

In [13]:
import numpy as np
tuple = zip(w1.columns, np.max(w1.values, axis=1))
sorted_items = sorted(tuple, key = lambda x:(x[1],x[0]), reverse =True)[:55]
sorted_items

[('재난', 0.9803265279649102),
 ('접촉자', 0.9517133378106686),
 ('접종', 0.9517133378106686),
 ('지도자', 0.9178802387797964),
 ('한반도', 0.9106534314801016),
 ('발동', 0.8731601983014741),
 ('인천', 0.8698326517100518),
 ('인증', 0.8698326517100518),
 ('얼마', 0.8553437275161645),
 ('글로벌', 0.8518707640646309),
 ('한경닷컴', 0.8414963635062084),
 ('사업장', 0.8374897087654309),
 ('기준금리', 0.8326780701228765),
 ('폐지', 0.8325924599739126),
 ('선생', 0.8322620939493834),
 ('포인트', 0.8311588394438157),
 ('초청', 0.8307931158512601),
 ('하향', 0.8298289495113055),
 ('철도', 0.8273924154756052),
 ('철강', 0.8265445614912253),
 ('무관', 0.8258602898100761),
 ('선물', 0.8248777127479222),
 ('노무현', 0.8238925816704827),
 ('영향력', 0.8238896423371339),
 ('유입', 0.8151553964695564),
 ('취업자', 0.8144290165852451),
 ('처방', 0.812911366264234),
 ('공원', 0.8124572782929825),
 ('분기', 0.8088629732864572),
 ('적자', 0.8055970545965451),
 ('임대', 0.8024730256007869),
 ('전제', 0.8005716297954367),
 ('약속', 0.7981986248616657),
 ('의식', 0.7924776193725203),
 ('미래통합당', 0.7907841262463358),
 ('기저질환', 0.7865467680026695),
 ('회사채', 0.7861285797472707),
 ('화장실', 0.7861285797472707),
 ('휴관', 0.7851318784605629),
 ('주택', 0.7827111663866126),
 ('박원순', 0.7812265795788953),
 ('프로', 0.780772322778932),
 ('폼페이오', 0.780772322778932),
 ('네덜란드', 0.7802444971589944),
 ('장기', 0.7785035090333449),
 ('국내총생산', 0.7770658421546066),
 ('구청장', 0.7770658421546066),
 ('교민들', 0.7770658421546066),
 ('공항', 0.7770658421546066),
 ('동행', 0.7770013971407679),
 ('커뮤니티', 0.7761152092854305),
 ('지지율', 0.7753795405870928),
 ('활용', 0.7748155887136723),
 ('인종', 0.773094754687841),
 ('인재', 0.773094754687841)]

In [14]:
w2 = word.loc[4552:7658,:] #MBC
w2

,000만,000명,000억,10,100,1000만,1000명,100만,100명,10년,...,휴대폰,휴식,휴업,휴원,휴직,흐름,흑인,흑자,희망,희생
4552,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.076812
4553,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000
4554,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000
4555,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.071325,0.0,0.0,0.0,0.000000
4556,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7654,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000
7655,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000
7656,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000
7657,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.057358,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000
7658,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000

In [17]:
import numpy as np
tuple = zip(w2.columns, np.max(w2.values, axis=1))
sorted_items = sorted(tuple, key = lambda x:(x[1],x[0]), reverse =True)[:61]
sorted_items

[('감수', 0.9443425405219869),
 ('완치자', 0.9025989442157952),
 ('내수', 0.9022530676676479),
 ('의석', 0.9012740213246828),
 ('대처', 0.8946943819385804),
 ('프로젝트', 0.8901502211166857),
 ('서로', 0.8887638225041976),
 ('전남', 0.8771918164584992),
 ('실험', 0.8739268446149652),
 ('개소', 0.87215717795077),
 ('재단', 0.8702920366423337),
 ('임직원', 0.8692882439626739),
 ('주도', 0.8678148972028509),
 ('100만', 0.8617956003942621),
 ('12명', 0.8588282581472921),
 ('5명', 0.8540854766396646),
 ('12월', 0.8492901370396562),
 ('정당', 0.8457558118378947),
 ('고조', 0.8455852154601836),
 ('프리미엄', 0.844208869586569),
 ('감시', 0.8429048865451401),
 ('선택', 0.8396075744619589),
 ('기숙사', 0.8390536042908783),
 ('화학', 0.8388857457105492),
 ('덕분', 0.8347623254187917),
 ('지능', 0.8346833881469659),
 ('직업', 0.8342969827398824),
 ('성사', 0.8337377916439951),
 ('연말', 0.8321340654914621),
 ('부모', 0.8315313614760116),
 ('비중', 0.8242756331698571),
 ('제일교회', 0.821874587156896),
 ('신임', 0.8211384402651923),
 ('지방', 0.8210872197028423),
 ('상징', 0.8201134069450228),
 ('유동', 0.8200882643531108),
 ('유출', 0.8164009820114575),
 ('14', 0.8157036925881034),
 ('지출', 0.8154439847021585),
 ('카페', 0.8152447054337778),
 ('크루즈', 0.8134984431753596),
 ('100', 0.8107721412793021),
 ('매수', 0.8093171748837488),
 ('향상', 0.8092065605472049),
 ('창출', 0.8079009807169691),
 ('코로나19', 0.8077522174194028),
 ('오픈', 0.8067993465884905),
 ('마이너스', 0.8046476894338893),
 ('혼자', 0.8040276560026913),
 ('회사채', 0.7994090281459659),
 ('범죄', 0.7985628827735719),
 ('애플', 0.7975633247458119),
 ('귀가', 0.7972610080935988),
 ('성공', 0.7970117418613508),
 ('2019년', 0.7965751119935809),
 ('전시', 0.7958442249532547),
 ('현실적', 0.7922957770155213),
 ('명단', 0.7916479064935211),
 ('전공', 0.7906283190427521),
 ('검체', 0.7883523843011432),
 ('진영', 0.7877138628964407)]

In [18]:
w3 = word.loc[7658:8886,:] #OBS
w3

,000만,000명,000억,10,100,1000만,1000명,100만,100명,10년,...,휴대폰,휴식,휴업,휴원,휴직,흐름,흑인,흑자,희망,희생
7658,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
7659,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
7660,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
7661,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
7662,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8882,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
8883,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
8884,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.190023,0.0
8885,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
8886,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0

In [20]:
import numpy as np
tuple = zip(w3.columns, np.max(w3.values, axis=1))
sorted_items = sorted(tuple, key = lambda x:(x[1],x[0]), reverse =True)[:71]
sorted_items

[('구체', 0.9426389521527204),
 ('면세점', 0.9184220973201764),
 ('과도', 0.8648829275992859),
 ('권한', 0.8598785552249498),
 ('과거', 0.8561973702839644),
 ('그다음', 0.8529601441771201),
 ('공기', 0.8509205428268285),
 ('리원량', 0.8499383414864746),
 ('sk', 0.8264046351372464),
 ('공중', 0.8250141226714348),
 ('200만', 0.8197733396931441),
 ('근로자', 0.8161570256824081),
 ('반박', 0.8116901785320322),
 ('간격', 0.8042057844421799),
 ('경제학', 0.7986661921951594),
 ('경제', 0.7949074190155098),
 ('고생', 0.7944791277429808),
 ('11', 0.7938344379041414),
 ('2단계', 0.7889138803657906),
 ('물자', 0.7831355325184172),
 ('5년', 0.7806495552520462),
 ('급여', 0.7804356700325631),
 ('30명', 0.773621210804013),
 ('bbc', 0.7733091251317429),
 ('바람', 0.7726550581103726),
 ('경계', 0.7702668786561111),
 ('cdc', 0.7680105397213902),
 ('기재부', 0.7670182593840504),
 ('2차', 0.7601766303604682),
 ('fed', 0.7559854292790243),
 ('17', 0.7494181162912562),
 ('10월', 0.7465997367263097),
 ('마스크', 0.7463421516343032),
 ('24', 0.7456580431288808),
 ('방해', 0.7439971290620472),
 ('복합', 0.7426669593770283),
 ('게시', 0.7386356954540643),
 ('29', 0.7337575920096489),
 ('김여정', 0.7318169168517027),
 ('기념', 0.7308251576811621),
 ('18일', 0.7288966781511786),
 ('면역력', 0.7251321393285215),
 ('매력', 0.7248175475168359),
 ('개봉', 0.7216396720829399),
 ('6일', 0.7202521467026487),
 ('59', 0.7190271961285803),
 ('고향', 0.7189357935711431),
 ('곤란', 0.7189000431665676),
 ('배려', 0.7183711490898443),
 ('대구교회', 0.7183535215185219),
 ('귀국', 0.7183426421413108),
 ('7명', 0.715380265668801),
 ('단행', 0.7152139075259815),
 ('물품', 0.7142495985210067),
 ('3월', 0.7130085053109493),
 ('대외', 0.7096132481203479),
 ('금요일', 0.7093854359229737),
 ('공부', 0.7078268273088467),
 ('국가주석', 0.7070476329901456),
 ('경북', 0.7045567940749343),
 ('국회', 0.7041613050677497),
 ('가수', 0.7031451812761894),
 ('계층', 0.7030705304253202),
 ('공식적', 0.6976324021043074),
 ('맥주', 0.6949785702791892),
 ('류재복', 0.693457183897809),
 ('경쟁', 0.6933490548137607),
 ('극장', 0.6920661633508323),
 ('매매', 0.6918933332133981),
 ('기소', 0.6917568209072),
 ('동행', 0.6907404582713084)]

In [21]:
w4 = word.loc[8886:10725,:] #SBS
w4

,000만,000명,000억,10,100,1000만,1000명,100만,100명,10년,...,휴대폰,휴식,휴업,휴원,휴직,흐름,흑인,흑자,희망,희생
8886,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8887,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8888,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8889,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8890,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10721,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10722,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10723,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10724,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10725,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [22]:
import numpy as np
tuple = zip(w4.columns, np.max(w4.values, axis=1))
sorted_items = sorted(tuple, key = lambda x:(x[1],x[0]), reverse =True)[:70]
sorted_items

[('고양시', 0.9041780373076036),
 ('매물', 0.8780546530519715),
 ('감소세', 0.8702959279860027),
 ('상점', 0.8686696680342532),
 ('농산물', 0.8615171569117056),
 ('만족', 0.8584609284220335),
 ('거대', 0.8552942243838348),
 ('오해', 0.8484961940429605),
 ('우한', 0.8455179628436779),
 ('수주', 0.8450014557804059),
 ('100만', 0.8438707846427826),
 ('대량', 0.8429961138830941),
 ('세기', 0.8374128010385785),
 ('ai', 0.8370900847281443),
 ('개선', 0.8316796361419322),
 ('국무', 0.8307899267149442),
 ('아동', 0.8301169515829954),
 ('200만', 0.8260153406819877),
 ('3일', 0.8242398389808747),
 ('긴장', 0.8223128190819659),
 ('안전성', 0.8222973401311093),
 ('신호', 0.8160193630075888),
 ('가속화', 0.8146062947212865),
 ('달러', 0.8081928334608901),
 ('28일', 0.8078223845137709),
 ('불안감', 0.8058874283151043),
 ('동참', 0.8054687737663508),
 ('물품', 0.8051896768285152),
 ('미국인', 0.803278173001015),
 ('경북', 0.8021940829179589),
 ('만기', 0.7955769835611924),
 ('67', 0.7948369222239384),
 ('대학', 0.7946986772350574),
 ('성명', 0.7918035367936442),
 ('신경', 0.7892512354614781),
 ('상장', 0.7892324972029165),
 ('20', 0.7889509000864172),
 ('10조', 0.7883811385377525),
 ('불필요', 0.7875989336903816),
 ('wsj', 0.7832200082309352),
 ('동네', 0.7827206356525773),
 ('기준', 0.782530292584277),
 ('경북도', 0.7813716350859055),
 ('불참', 0.7810478052479591),
 ('보건복지부', 0.7802845656186503),
 ('본부', 0.7801724666390061),
 ('상시', 0.7797654727126745),
 ('마켓', 0.7787724395907953),
 ('강사', 0.7777495654617751),
 ('방역', 0.777697448642766),
 ('실장', 0.7742938590922309),
 ('대기업', 0.7742674447835919),
 ('동기', 0.7740337283381814),
 ('거래일', 0.7735470802782177),
 ('기업', 0.7735194787571698),
 ('세종', 0.7729260545401476),
 ('업소', 0.77230739201827),
 ('국산', 0.7711301572674342),
 ('거브러여수스', 0.7683653702124112),
 ('개장', 0.7673607762885649),
 ('cj', 0.7670719854218792),
 ('100', 0.7660906433309986),
 ('비말', 0.7636732291799371),
 ('사용', 0.7625613246948513),
 ('거주자', 0.7599060598563642),
 ('경증', 0.759407236150624),
 ('경험', 0.7593406192825043),
 ('박람회', 0.7578456219116528),
 ('5년', 0.7549815182478646),
 ('구청', 0.7547240997170007)]

In [23]:
w5 = word.loc[10725:19999,:] #YTN
w5

,000만,000명,000억,10,100,1000만,1000명,100만,100명,10년,...,휴대폰,휴식,휴업,휴원,휴직,흐름,흑인,흑자,희망,희생
10725,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
10726,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
10727,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
10728,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
10729,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.052189,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
19996,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
19997,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.020297,0.0
19998,0.0,0.0,0.0,0.0,0.0,0.023914,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
19999,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0

In [24]:
import numpy as np
tuple = zip(w5.columns, np.max(w5.values, axis=1))
sorted_items = sorted(tuple, key = lambda x:(x[1],x[0]), reverse =True)[:65]
sorted_items

[('보상', 0.9535852770068921),
 ('소수', 0.934004911834182),
 ('규정', 0.9168748384167826),
 ('lg', 0.9015248189404476),
 ('블루', 0.8944127209042179),
 ('부분들', 0.8877909430367253),
 ('소득', 0.8874212998905138),
 ('사람', 0.8874212998905138),
 ('감염자', 0.8812178302116933),
 ('etf', 0.8788405889953022),
 ('94', 0.8788405889953022),
 ('폐업', 0.8601269972683491),
 ('업체', 0.859886580527705),
 ('연준', 0.8549100062370671),
 ('치명률', 0.8537743746156875),
 ('역대', 0.8534510585297168),
 ('철강', 0.8530164942829853),
 ('존재', 0.851573993816125),
 ('집중', 0.8454062195640958),
 ('조언', 0.8424282915425233),
 ('실제', 0.8419557509093452),
 ('1위', 0.8407140461205195),
 ('보급', 0.8398507728473189),
 ('시민', 0.8375030481643697),
 ('격상', 0.8336083641794922),
 ('남성', 0.8319364891869702),
 ('팀장', 0.8314656905381312),
 ('절차', 0.8300613661954561),
 ('심의', 0.8286446713692841),
 ('통화', 0.8277806084726675),
 ('예능', 0.8197335301770651),
 ('남부', 0.8187847751070907),
 ('기타', 0.8187847751070907),
 ('유권자들', 0.8185000103222065),
 ('일상', 0.8184350553639391),
 ('제도', 0.8149862664694083),
 ('8시', 0.8147815399448356),
 ('단독', 0.8130676877410333),
 ('연기', 0.8118274554931832),
 ('12', 0.8093314983659994),
 ('운동', 0.8086142677132401),
 ('서울대', 0.8080411596091447),
 ('개편', 0.8078981747186421),
 ('풀이', 0.8072929239458045),
 ('가지', 0.8072553639402383),
 ('유리', 0.8054165869615597),
 ('점포', 0.8047069241764352),
 ('협의회', 0.8047012828524237),
 ('해외여행', 0.8024781871563871),
 ('고령자', 0.8013700024983006),
 ('가짜', 0.7995096480996242),
 ('85', 0.7991146169684513),
 ('의존도', 0.7987814968829543),
 ('후보자', 0.7974428636034685),
 ('실태', 0.7972917353007535),
 ('주체', 0.7972850017782382),
 ('현지', 0.7972577680261521),
 ('인공지능', 0.7944934249620813),
 ('삼성', 0.7941875732311295),
 ('의뢰', 0.7934354004659334),
 ('시가', 0.7889746233482512),
 ('학생들', 0.7887783622563166),
 ('할인', 0.7886194696880485),
 ('제안', 0.7818771487245451),
 ('체감', 0.7815085351559152)]

In [26]:
w6 = word.loc[19999:23787,:] #경향신문
w6

,000만,000명,000억,10,100,1000만,1000명,100만,100명,10년,...,휴대폰,휴식,휴업,휴원,휴직,흐름,흑인,흑자,희망,희생
19999,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20001,0.0,0.0,0.0,0.0,0.0,0.056385,0.0,0.04848,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20002,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20003,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.301806,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23783,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23784,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23785,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23786,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23787,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [27]:
tuple = zip(w6.columns, np.max(w6.values, axis=1))
sorted_items = sorted(tuple, key = lambda x:(x[1],x[0]), reverse =True)[:70]
sorted_items

[('패널', 0.9527220198876236),
 ('죽음', 0.9460360865727244),
 ('염두', 0.9408857030546284),
 ('일요일', 0.9302526802555572),
 ('선언', 0.9270168376224688),
 ('기구', 0.9188949763358342),
 ('취임', 0.918375909525284),
 ('제조업', 0.9147257943833604),
 ('자동차', 0.9083334372484084),
 ('배치', 0.9037311589836434),
 ('병원', 0.8936313477776026),
 ('움직임', 0.8904160821152224),
 ('부모', 0.8818077524154224),
 ('주제', 0.8720655941696003),
 ('지하', 0.8688844010827335),
 ('각오', 0.8603325305764599),
 ('선정', 0.8591459072834317),
 ('유발', 0.8542096174197673),
 ('정규', 0.8484466524841977),
 ('200만', 0.8451796015858619),
 ('핵심', 0.8421881732300118),
 ('전체적', 0.8412605264396009),
 ('세미나', 0.8410153716931585),
 ('주의', 0.838667669693701),
 ('발송', 0.8386530763996293),
 ('수상', 0.8382431304435463),
 ('변호사', 0.8378538939730984),
 ('조기', 0.8352942248773542),
 ('프로그램', 0.8338246583398707),
 ('대응', 0.8324125548237958),
 ('한시적', 0.8319480616170751),
 ('활성화', 0.8261252358709367),
 ('마감', 0.8253696750465762),
 ('마켓', 0.8242225175645461),
 ('패키지', 0.8227288322540341),
 ('국장', 0.8216174729840201),
 ('개설', 0.8200467680873164),
 ('직장인', 0.8193650561949051),
 ('해수욕장', 0.8178735694171427),
 ('거점', 0.8174354471567973),
 ('ai', 0.8161508839761141),
 ('쿠팡', 0.8150202223333075),
 ('동시', 0.8134739962612391),
 ('고비', 0.8129957066434559),
 ('단지', 0.8125292844648383),
 ('1주일', 0.8120825364514607),
 ('시간', 0.8115122062565383),
 ('sk하이닉스', 0.8085550442650293),
 ('여지', 0.8077716904674415),
 ('7시', 0.8077070295737967),
 ('비전', 0.8073344814958799),
 ('의문', 0.8050282330072296),
 ('부양책', 0.8042589259539449),
 ('거브러여수스', 0.8036772668664577),
 ('전시', 0.8026781064616897),
 ('감소세', 0.8013159204083045),
 ('대학원', 0.8005190604466949),
 ('구축', 0.8002722974353116),
 ('전세기', 0.8002556547586779),
 ('표시', 0.7992332750658205),
 ('중국', 0.7986130789870367),
 ('인생', 0.7972483581532653),
 ('반납', 0.7972479722566602),
 ('네덜란드', 0.7971678952651653),
 ('애로', 0.7955151734445012),
 ('기초', 0.7943347278906095),
 ('김정은', 0.7939995295223509),
 ('효율', 0.7936516482907268),
 ('의미', 0.7932760601263321),
 ('성사', 0.7918496054157091)]

In [28]:
w7 = word.loc[23787:31627,:] #국민일보
w7

,000만,000명,000억,10,100,1000만,1000명,100만,100명,10년,...,휴대폰,휴식,휴업,휴원,휴직,흐름,흑인,흑자,희망,희생
23787,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
23788,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
23789,0.0,0.0,0.0,0.053681,0.0,0.0,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.064456,0.0,0.0,0.000000,0.0
23790,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
23791,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.055398,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31623,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
31624,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.058252,0.0,0.0,0.000000,0.0
31625,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.02646,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
31626,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
31627,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.044113,0.0

In [29]:
tuple = zip(w7.columns, np.max(w7.values, axis=1))
sorted_items = sorted(tuple, key = lambda x:(x[1],x[0]), reverse =True)[:70]
sorted_items

[('시리즈', 0.9464912804582836),
 ('매도', 0.9298908904179636),
 ('신장', 0.9266844416108342),
 ('sk하이닉스', 0.916843185706176),
 ('20만', 0.9130791240141104),
 ('ai', 0.9084634745086296),
 ('200만', 0.9021162408533838),
 ('3개월', 0.8991705879460445),
 ('안정', 0.8966305737435625),
 ('추산', 0.8899515287955386),
 ('경영자', 0.8795250830684836),
 ('대면', 0.8719099431676851),
 ('위상', 0.8653788096658735),
 ('건의', 0.8632788893170896),
 ('가족들', 0.86200659642528),
 ('상점', 0.8590310404358269),
 ('가짜뉴스', 0.8571497104524778),
 ('교수', 0.8570900879047023),
 ('도약', 0.855272610294362),
 ('생활', 0.8537087055055989),
 ('60대', 0.8529855529320716),
 ('복구', 0.852605419620446),
 ('광주시', 0.8523192351154724),
 ('영어', 0.8519580213193907),
 ('참고', 0.8513317174537174),
 ('소진', 0.8511974952549656),
 ('편지', 0.8500242627134448),
 ('소요', 0.8489398573065562),
 ('무리', 0.8479053792581257),
 ('지급', 0.8440819140301357),
 ('상임', 0.8402385426222821),
 ('지능', 0.8386558743922496),
 ('공천', 0.8378853938660016),
 ('예술', 0.8375937595262558),
 ('각국', 0.8370365593957996),
 ('국가들', 0.8339005580839859),
 ('인기', 0.8315865015252579),
 ('그동안', 0.831406886795543),
 ('실험', 0.8306523303381667),
 ('당선', 0.8293571766102479),
 ('경제활동', 0.8292883926103092),
 ('원내', 0.8274955717828829),
 ('모집', 0.8266612982388831),
 ('소수', 0.8254039855412177),
 ('관람', 0.8253368752145087),
 ('진영', 0.8252308205841407),
 ('필수', 0.8243360288201282),
 ('42', 0.8219206834697064),
 ('유리', 0.8217859667351969),
 ('연출', 0.8195229704415955),
 ('초등학교', 0.8175085212242),
 ('것들', 0.8173451454033116),
 ('삭감', 0.817297700190759),
 ('시작', 0.8146357218205752),
 ('소장', 0.813475305977737),
 ('분기', 0.8129686488298915),
 ('8시', 0.8124885531748515),
 ('사이버', 0.8111262639129645),
 ('진실', 0.8101226891282561),
 ('제작', 0.8101075959585913),
 ('걱정', 0.8100543768312973),
 ('3조', 0.8099045853111478),
 ('기부', 0.8086764669388449),
 ('댓글', 0.8084058232438973),
 ('수업', 0.8073533145472717),
 ('부진', 0.8070820463651873),
 ('화제', 0.8058205683407875),
 ('동일', 0.8054626997894507),
 ('개념', 0.8052425658155129),
 ('대체', 0.802803455761548)]

In [30]:
w8 = word.loc[31627:33608,:] #내일신문
w8

,000만,000명,000억,10,100,1000만,1000명,100만,100명,10년,...,휴대폰,휴식,휴업,휴원,휴직,흐름,흑인,흑자,희망,희생
31627,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.00000,0.0,0.0,0.044113,0.0
31628,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.04394,0.0,0.0,0.020068,0.0
31629,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.052392,0.0,0.0,0.00000,0.0,0.0,0.000000,0.0
31630,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.00000,0.0,0.0,0.000000,0.0
31631,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.00000,0.0,0.0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33604,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.00000,0.0,0.0,0.000000,0.0
33605,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.00000,0.0,0.0,0.000000,0.0
33606,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.154530,0.0,0.0,0.00000,0.0,0.0,0.000000,0.0
33607,0.0,0.0,0.0,0.0,0.042974,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.00000,0.0,0.0,0.296601,0.0
33608,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.00000,0.0,0.0,0.000000,0.0

In [31]:
tuple = zip(w8.columns, np.max(w8.values, axis=1))
sorted_items = sorted(tuple, key = lambda x:(x[1],x[0]), reverse =True)[:70]
sorted_items

[('감산', 0.9538215354814986),
 ('기재부', 0.8852917073718953),
 ('긴급재난지원금', 0.8830655498328996),
 ('배우', 0.8807661990784934),
 ('수지', 0.8708803620951883),
 ('의료기관', 0.865842501810353),
 ('비즈니스', 0.8647563514352767),
 ('경쟁력', 0.8573210346578126),
 ('우한시', 0.857248255524216),
 ('보호', 0.8508950035499984),
 ('상처', 0.8473921954847242),
 ('경계', 0.8375303869899727),
 ('쌍용차', 0.832966905102434),
 ('7월', 0.8309884686771262),
 ('기저질환', 0.8276308576984326),
 ('단순', 0.8269857356772394),
 ('3분', 0.8263855846640732),
 ('18일', 0.8256867092817393),
 ('수출액', 0.8182722289400874),
 ('시내', 0.8170504034440749),
 ('물품', 0.8168616573022319),
 ('거점', 0.8152848888973689),
 ('산하', 0.8142164075308433),
 ('경신', 0.8117464526287106),
 ('극복', 0.8062228943889238),
 ('박사', 0.8035318668560113),
 ('업체들', 0.7979141475106276),
 ('부지', 0.7975020514063081),
 ('내각', 0.7968678232000614),
 ('근로자', 0.7912584139368736),
 ('영국', 0.7907278689320227),
 ('약화', 0.7889781418075392),
 ('나름', 0.7889508760136491),
 ('강도', 0.7864915984939483),
 ('각지', 0.7857347479150744),
 ('유동성', 0.7852545654823101),
 ('30', 0.7823203494805786),
 ('보급', 0.7811578860229712),
 ('노래', 0.7801881122908393),
 ('상장', 0.7792735532838545),
 ('비교', 0.7775445120488136),
 ('소득', 0.7747258124930821),
 ('기생충', 0.7733631519086017),
 ('부회장', 0.7715711118453479),
 ('실질', 0.7708979882614536),
 ('위원장', 0.7707986024422263),
 ('개정안', 0.7689064937974825),
 ('사람', 0.7667718726544561),
 ('무관', 0.7667073532531731),
 ('여자', 0.7661823026546224),
 ('만족', 0.7621566741260103),
 ('대면', 0.7610255088147814),
 ('수립', 0.7608785260951955),
 ('세제', 0.7601970420610615),
 ('사업자', 0.7601896160251436),
 ('부각', 0.759625669865272),
 ('세대', 0.7590999693821744),
 ('개최', 0.7567219564388314),
 ('대표적', 0.7565603096112188),
 ('공조', 0.7561967290779363),
 ('경쟁', 0.7555394713055763),
 ('유출', 0.7553315978667395),
 ('요구', 0.7538481263402259),
 ('관세', 0.7529967684524705),
 ('공무원', 0.7513998536547527),
 ('마포구', 0.7511638104370905),
 ('시절', 0.7510366581460207),
 ('교류', 0.7506812480503707),
 ('법무부', 0.7482741871478382),
 ('2015년', 0.7477600017899538)]

In [32]:
w9 = word.loc[33608:38094,:] #동아일보
w9

,000만,000명,000억,10,100,1000만,1000명,100만,100명,10년,...,휴대폰,휴식,휴업,휴원,휴직,흐름,흑인,흑자,희망,희생
33608,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
33609,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
33610,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
33611,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.059608,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
33612,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38090,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
38091,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.197762,0.0
38092,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
38093,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
38094,0.0,0.0,0.0,0.0,0.0,0.04489,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0

In [33]:
tuple = zip(w9.columns, np.max(w9.values, axis=1))
sorted_items = sorted(tuple, key = lambda x:(x[1],x[0]), reverse =True)[:70]
sorted_items

[('발의', 1.0),
 ('예측', 0.9205049546616552),
 ('에어컨', 0.9121102467833944),
 ('부본부장', 0.9067942041337214),
 ('여자', 0.905284609174438),
 ('식량', 0.8992310769146651),
 ('작성', 0.898429849510533),
 ('컴퓨터', 0.8902732340977526),
 ('차세대', 0.8891640583774277),
 ('매각', 0.8873201912886455),
 ('책임자', 0.8870735979012262),
 ('물자', 0.8862605046593934),
 ('연대', 0.8814655690344303),
 ('개장', 0.8810535478616904),
 ('처분', 0.8783783503092609),
 ('활성화', 0.8768718496425569),
 ('좌석', 0.8760952536324714),
 ('반납', 0.8698413874987962),
 ('연구소', 0.8694193078950752),
 ('3개', 0.8664168767023482),
 ('프로그램', 0.8649950154713407),
 ('취득', 0.8594866811188678),
 ('상임위', 0.8556010171235158),
 ('영세', 0.8555278072586353),
 ('서울시', 0.8530562065232487),
 ('마포구', 0.8515608978884044),
 ('최저', 0.8499282163466622),
 ('총액', 0.8491585256718981),
 ('제한', 0.8487986822180205),
 ('치열', 0.8461636713452387),
 ('서비스', 0.8441836742949375),
 ('역사', 0.8429071829672937),
 ('전염', 0.8426842928852079),
 ('방안', 0.8416508024709402),
 ('조율', 0.8395587232130656),
 ('지출', 0.8381897797603176),
 ('골프', 0.8370089805240744),
 ('말레이시아', 0.8349505575447381),
 ('부정', 0.8347050947937145),
 ('기기', 0.8335015496588704),
 ('개국', 0.8333115900463367),
 ('주말', 0.8326455760831191),
 ('채권', 0.8325374356313704),
 ('본인', 0.8292481966385854),
 ('사무실', 0.8238240901744159),
 ('집값', 0.8226431130631303),
 ('주식시장', 0.8206994052982189),
 ('운영', 0.8197064490077046),
 ('카드', 0.8173100459645603),
 ('사정', 0.8171291709033338),
 ('혼자', 0.8163818115507251),
 ('계약', 0.8112217692758044),
 ('3개월', 0.8098229698855675),
 ('로이터통신', 0.8094312014223582),
 ('올림픽', 0.8086963873222619),
 ('공천', 0.8073300413648239),
 ('개인', 0.8063413973076938),
 ('소상공인', 0.8046346528907088),
 ('한은', 0.8040657635246699),
 ('정의', 0.8020308209632238),
 ('기숙사', 0.801418159399672),
 ('발령', 0.7996766564634148),
 ('공식적', 0.7967496087882294),
 ('주체', 0.7966454949327171),
 ('현실화', 0.7964324347843149),
 ('사진', 0.7963514857067235),
 ('증시', 0.7958997315489034),
 ('회원', 0.7950895249306507),
 ('싸움', 0.794601558734777),
 ('우선', 0.7933298526139549)]

In [34]:
w10 = word.loc[38094:48522,:] #매일경제
w10

,000만,000명,000억,10,100,1000만,1000명,100만,100명,10년,...,휴대폰,휴식,휴업,휴원,휴직,흐름,흑인,흑자,희망,희생
38094,0.0,0.00000,0.0,0.0,0.0,0.04489,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
38095,0.0,0.00000,0.0,0.0,0.0,0.00000,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
38096,0.0,0.06151,0.0,0.0,0.0,0.00000,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
38097,0.0,0.00000,0.0,0.0,0.0,0.00000,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
38098,0.0,0.00000,0.0,0.0,0.0,0.00000,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.056598,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48518,0.0,0.00000,0.0,0.0,0.0,0.00000,0.0,0.042626,0.0,0.0,...,0.0,0.0,0.126167,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
48519,0.0,0.00000,0.0,0.0,0.0,0.00000,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
48520,0.0,0.00000,0.0,0.0,0.0,0.00000,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
48521,0.0,0.00000,0.0,0.0,0.0,0.00000,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
48522,0.0,0.00000,0.0,0.0,0.0,0.00000,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0

In [35]:
tuple = zip(w10.columns, np.max(w10.values, axis=1))
sorted_items = sorted(tuple, key = lambda x:(x[1],x[0]), reverse =True)[:70]
sorted_items

[('외신', 0.9361857655534591),
 ('종교', 0.9212021328390972),
 ('라인', 0.9171308744988376),
 ('5명', 0.9009439833786506),
 ('현실화', 0.8931505498904444),
 ('침해', 0.892906641735293),
 ('순위', 0.8921194477962946),
 ('20만', 0.8873411629347681),
 ('1000명', 0.8851169206236892),
 ('2월', 0.8846764674784235),
 ('조달', 0.881176715010577),
 ('기회', 0.8810921465553908),
 ('보상', 0.8781712695626999),
 ('인공호흡기', 0.86821423012111),
 ('출입', 0.8678777535087854),
 ('인수', 0.8665124281295066),
 ('비즈니스', 0.8628465902835527),
 ('지지', 0.8578303750386248),
 ('근본적', 0.8529210515367648),
 ('교민', 0.8525577884380169),
 ('철강', 0.8495125459327136),
 ('제일교회', 0.8438397049758747),
 ('전개', 0.8408628362732671),
 ('고객들', 0.8406799094324838),
 ('여객', 0.8394565107181249),
 ('손소독제', 0.8387574114000408),
 ('기부금', 0.8382494293284548),
 ('wp', 0.8377330589922578),
 ('교민들', 0.8350452881069276),
 ('조성', 0.8341297938045295),
 ('중앙정부', 0.8307648869310088),
 ('보건', 0.8291203342354437),
 ('유사', 0.8286809314526954),
 ('촉구', 0.8259564968813747),
 ('사장', 0.8251598755897097),
 ('학생들', 0.8249328372462528),
 ('병행', 0.8240402055321859),
 ('사항', 0.8219485673475707),
 ('신속', 0.8203957030245058),
 ('의식', 0.815524047942328),
 ('게시', 0.8146294961795776),
 ('36', 0.8137247063860775),
 ('선임', 0.8114302513172541),
 ('메뉴', 0.8111399439752043),
 ('실장', 0.8099564732906107),
 ('부실', 0.8061146662074569),
 ('연기', 0.8053271335204787),
 ('수칙', 0.8002387382328621),
 ('전시', 0.7994512811357156),
 ('실업자', 0.7958301748087223),
 ('매수', 0.7944750378395149),
 ('무게', 0.7939874830802675),
 ('마이너스', 0.7932800714434334),
 ('전수', 0.7919654742254516),
 ('카카오', 0.7896048238912912),
 ('미래', 0.7893059657525571),
 ('13명', 0.7892559463068586),
 ('보좌관', 0.789040174095657),
 ('인구', 0.7876679222728571),
 ('전망', 0.7858122198148975),
 ('소통', 0.7858019906120481),
 ('중국인', 0.7855093610163036),
 ('보호', 0.7853939638007742),
 ('모델', 0.7851331323038946),
 ('설득', 0.7837986506443381),
 ('종합적', 0.7828410556459932),
 ('최우선', 0.7823874923830519),
 ('청년들', 0.7813678819749216),
 ('구성', 0.7802888827094719),
 ('귀국', 0.7796317837092825)]

In [36]:
w11 = word.loc[48522:63931,:] #머니투데이
w11

,000만,000명,000억,10,100,1000만,1000명,100만,100명,10년,...,휴대폰,휴식,휴업,휴원,휴직,흐름,흑인,흑자,희망,희생
48522,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
48523,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
48524,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
48525,0.0,0.0,0.0,0.021469,0.027294,0.031891,0.0,0.02742,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
48526,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63927,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.124899,0.0,0.0,0.0,0.0,0.0,0.0
63928,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
63929,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
63930,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
63931,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0

In [37]:
tuple = zip(w11.columns, np.max(w11.values, axis=1))
sorted_items = sorted(tuple, key = lambda x:(x[1],x[0]), reverse =True)[:70]
sorted_items

[('여성', 0.92321327806335),
 ('베이징', 0.8866180619793999),
 ('계획', 0.8838034546042207),
 ('훈련', 0.8806881403551686),
 ('농가', 0.8772858160128308),
 ('붕괴', 0.8748952205287167),
 ('학습', 0.8735349021339613),
 ('유권자들', 0.8698917000718259),
 ('의협', 0.8694165492090812),
 ('인류', 0.8662755549163684),
 ('진영', 0.8659298760905229),
 ('자사', 0.8574462254086822),
 ('제외', 0.8510299223355547),
 ('제거', 0.848311534441347),
 ('식사', 0.8445305428268957),
 ('cdc', 0.8387330051198332),
 ('환자들', 0.837686055407257),
 ('설명회', 0.836122356111564),
 ('추이', 0.8341045425539696),
 ('의심', 0.8306752721128926),
 ('이래', 0.8280899345927624),
 ('초기', 0.8280195162594807),
 ('취급', 0.8256927573075298),
 ('구체적', 0.8236241951882792),
 ('반환', 0.8224169438442399),
 ('시진핑', 0.8180849536544809),
 ('회의', 0.8176613625085922),
 ('정식', 0.816676051319206),
 ('임명', 0.8165010030453465),
 ('어려움', 0.8121112515309434),
 ('순위', 0.8094150378968915),
 ('완성', 0.8088488017617476),
 ('중앙정부', 0.8065865740489829),
 ('지역경제', 0.805756595406229),
 ('벤처', 0.8049245716762125),
 ('안내문', 0.8044686063669318),
 ('일간', 0.803531736891716),
 ('재원', 0.7990123950645484),
 ('간담회', 0.7988316384736671),
 ('3개', 0.7983053592270912),
 ('인도네시아', 0.7977849888224381),
 ('해소', 0.7960559075695323),
 ('교류', 0.7959120713841852),
 ('수용', 0.7950804475816226),
 ('무시', 0.7938932247061766),
 ('성남', 0.7928135048829754),
 ('리스크', 0.7914695694185894),
 ('지능', 0.7893297000529523),
 ('박원순', 0.7866902773158572),
 ('허가', 0.7842370949640979),
 ('보건부', 0.7827065472008975),
 ('상권', 0.7818398328776152),
 ('소득', 0.78098893972131),
 ('취임', 0.7806597204293827),
 ('수석', 0.7766449638938093),
 ('유치', 0.7755961341709916),
 ('삭제', 0.775544358854443),
 ('별도', 0.7754332817089312),
 ('생중계', 0.7747294017800664),
 ('전례', 0.7745126562748395),
 ('자치', 0.7740621252380198),
 ('여야', 0.7735243175926575),
 ('수술', 0.7731530274487892),
 ('실질적', 0.7731323776243548),
 ('호주', 0.7728141143874039),
 ('감염경로', 0.7725548622070821),
 ('현황', 0.7707469050068532),
 ('당내', 0.7704692221410087),
 ('동원', 0.7691690038268125),
 ('회동', 0.7687585361379857)]

In [38]:
w12 = word.loc[63931:66755,:] #문화일보
w12

,000만,000명,000억,10,100,1000만,1000명,100만,100명,10년,...,휴대폰,휴식,휴업,휴원,휴직,흐름,흑인,흑자,희망,희생
63931,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
63932,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
63933,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.110783,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
63934,0.0,0.0,0.0,0.197752,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
63935,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66751,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
66752,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.267863,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
66753,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
66754,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
66755,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [39]:
tuple = zip(w12.columns, np.max(w12.values, axis=1))
sorted_items = sorted(tuple, key = lambda x:(x[1],x[0]), reverse =True)[:70]
sorted_items

[('류재복', 0.9730297049866541),
 ('동기', 0.9058226433241932),
 ('교사', 0.9014744922243408),
 ('전문가', 0.8983207240335614),
 ('영상편집', 0.8981337582896939),
 ('그다음', 0.8796129882945836),
 ('관심', 0.8765174041968175),
 ('촉발', 0.8695315274550324),
 ('인도네시아', 0.8568816873632619),
 ('제재', 0.8544962363625619),
 ('침방울', 0.8485110880206879),
 ('100', 0.847226885998486),
 ('주간', 0.8455164263592561),
 ('지지율', 0.8452718105319593),
 ('평화', 0.8424516620530027),
 ('서구', 0.8329472154537604),
 ('밀폐', 0.8328993614571653),
 ('주가', 0.8311486892191411),
 ('풀이', 0.8294003995246362),
 ('식약처', 0.8264983112837329),
 ('감정', 0.8213406966831029),
 ('결합', 0.8145746449693324),
 ('동반', 0.8138908323260116),
 ('교섭', 0.8103315277748924),
 ('테스트', 0.8084750555854661),
 ('기지', 0.8070829259537637),
 ('생활', 0.8062949062778262),
 ('tf', 0.8061344231290145),
 ('출전', 0.8046378866807615),
 ('음식', 0.8040622459563048),
 ('정작', 0.8038576998072609),
 ('강도', 0.7996781649837664),
 ('봉쇄령', 0.7995085594452941),
 ('계기', 0.7986548841116464),
 ('청구', 0.7958693682887064),
 ('학교', 0.7952728159631578),
 ('관리', 0.7942601778011884),
 ('기소', 0.7940089474575067),
 ('경로', 0.7920132721754525),
 ('계정', 0.7911676891708758),
 ('둔화', 0.7909413121255042),
 ('표명', 0.7898966401636514),
 ('성명', 0.7898616979974306),
 ('피부', 0.7876260392555076),
 ('참석', 0.7873020501238609),
 ('차원', 0.7852342656743075),
 ('임직원', 0.7843617174733487),
 ('국립중앙의료원', 0.7812438983920935),
 ('소외', 0.7780286935286522),
 ('김혜민', 0.7769610596642966),
 ('중앙은행', 0.7768847467195338),
 ('두려움', 0.7757181013233719),
 ('박람회', 0.7751294500875423),
 ('폭증', 0.7751165770028677),
 ('돌입', 0.7739318817966929),
 ('명령', 0.7733415664684835),
 ('자회사', 0.7731256217338304),
 ('신청자', 0.7727347192542503),
 ('번째', 0.7699914604344307),
 ('집값', 0.7673385666293693),
 ('영등포구', 0.7670687518126098),
 ('2주', 0.7666812517156963),
 ('유동', 0.766423682171558),
 ('중순', 0.7655774174686851),
 ('인근', 0.7643260242172905),
 ('생산', 0.7641392053902935),
 ('기한', 0.7639785276195905),
 ('4일', 0.7632242484619199),
 ('선도', 0.7626256908565952),
 ('파업', 0.7621143259733771)]

In [48]:
w13 = word.loc[66755:77132,:] #서울경제
w13

,000만,000명,000억,10,100,1000만,1000명,100만,100명,10년,...,휴대폰,휴식,휴업,휴원,휴직,흐름,흑인,흑자,희망,희생
66755,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
66756,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.066583,0.0
66757,0.0,0.0,0.055902,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
66758,0.0,0.0,0.101536,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
66759,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77128,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
77129,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
77130,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
77131,0.0,0.0,0.000000,0.0,0.021471,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
77132,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0

In [49]:
tuple = zip(w13.columns, np.max(w13.values, axis=1))
sorted_items = sorted(tuple, key = lambda x:(x[1],x[0]), reverse =True)[:70]
sorted_items

[('가족', 1.0),
 ('임대료', 0.9910856990807048),
 ('결제', 0.9910856990807048),
 ('개장', 0.9910856990807048),
 ('용인시', 0.9779005144181364),
 ('배달', 0.9657084006613568),
 ('흑인', 0.9363074856875856),
 ('양보', 0.9317664047115932),
 ('기준금리', 0.9197700690262072),
 ('영역', 0.9129120528916388),
 ('면역', 0.9076318068209991),
 ('소식', 0.9002269277057917),
 ('계절', 0.9001507513179261),
 ('개국', 0.8954582278845736),
 ('부정', 0.893790272841953),
 ('조직', 0.8760982760699854),
 ('외식', 0.8730133421194687),
 ('인생', 0.8690038860291034),
 ('삭감', 0.8669838748736529),
 ('합동', 0.863329184622317),
 ('혁신', 0.8632502256233391),
 ('당장', 0.8590755255287296),
 ('인천시', 0.8572830036641343),
 ('환영', 0.8551531196193406),
 ('역할', 0.8540003436228814),
 ('기소', 0.8524410830893007),
 ('보완', 0.8496042566626784),
 ('지역감염', 0.8490273316734029),
 ('동네', 0.8417410683890996),
 ('진단검사', 0.8414300919743174),
 ('lg전자', 0.8395242435611393),
 ('대상', 0.8380760411407658),
 ('회동', 0.8364174515924587),
 ('집값', 0.8361928633515937),
 ('전형', 0.8320171363427836),
 ('해석', 0.8179024930348164),
 ('뉴딜', 0.8176179713436096),
 ('30', 0.8165056172827613),
 ('주택', 0.8140939857423342),
 ('서민', 0.8123107986017467),
 ('석유', 0.8116682819003274),
 ('광화문', 0.8108849233250515),
 ('적용', 0.8096108362897932),
 ('지속', 0.8082324600039975),
 ('민원', 0.8058838130686575),
 ('행동', 0.8046656841477634),
 ('9일', 0.8023542526535159),
 ('공연', 0.8021985068141656),
 ('공원', 0.7996987679985976),
 ('민심', 0.7993952758147171),
 ('18', 0.7993538150590616),
 ('국민', 0.7954476659944726),
 ('완전', 0.7951894510416072),
 ('파리', 0.7933034588551073),
 ('공시', 0.7927881765920872),
 ('발령', 0.7917361436203617),
 ('신경', 0.7916766984956599),
 ('하향', 0.7914883937574922),
 ('경신', 0.7876969049904559),
 ('폐지', 0.7876752662522811),
 ('육성', 0.7872193842868431),
 ('웃음', 0.7870025125264094),
 ('정례', 0.7853347472797663),
 ('34', 0.7849197762828132),
 ('국적', 0.784044096645962),
 ('대유행', 0.783445012223016),
 ('43', 0.7831855261943969),
 ('출전', 0.7811956439370116),
 ('스트레스', 0.7811541695024828),
 ('설정', 0.7807668056826512)]

In [50]:
w14 = word.loc[77132:84031,:] #서울신문
w14

,000만,000명,000억,10,100,1000만,1000명,100만,100명,10년,...,휴대폰,휴식,휴업,휴원,휴직,흐름,흑인,흑자,희망,희생
77132,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
77133,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
77134,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
77135,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
77136,0.0,0.0,0.0,0.0,0.057741,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84027,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
84028,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.125303,0.0,0.0,0.0,0.0,0.0,0.0,0.0
84029,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
84030,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
84031,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [51]:
tuple = zip(w14.columns, np.max(w14.values, axis=1))
sorted_items = sorted(tuple, key = lambda x:(x[1],x[0]), reverse =True)[:70]
sorted_items

[('일선', 0.9755264327634624),
 ('가입자', 0.9268586832223308),
 ('평소', 0.9147456167696876),
 ('코로나', 0.8999262960223974),
 ('선대', 0.8996347352956147),
 ('9월', 0.8866333733683219),
 ('협상', 0.8833375014924708),
 ('11시', 0.879870993348884),
 ('어려움', 0.8766912998171047),
 ('혼자', 0.8732951166140202),
 ('혼란', 0.8732951166140202),
 ('대한항공', 0.8719464943162963),
 ('증권', 0.8638197398045724),
 ('한시적', 0.8629262058289228),
 ('지속', 0.8615915404218155),
 ('검사', 0.8589931054757246),
 ('편리', 0.8543146725221626),
 ('99', 0.8540797357681904),
 ('기생충', 0.8473150702348826),
 ('만남', 0.8451698413265402),
 ('주식시장', 0.8451007095136871),
 ('의류', 0.8449854836200541),
 ('유동성', 0.8447381472769053),
 ('방안', 0.8444983988691727),
 ('공단', 0.8427403774425632),
 ('만전', 0.8419636223251795),
 ('전반', 0.8415310121748051),
 ('농촌', 0.8387616786387521),
 ('화면', 0.8340115610914733),
 ('대목', 0.8321520728455988),
 ('설치', 0.8313078799148276),
 ('호소', 0.8288695176537934),
 ('이만희', 0.8286831371519704),
 ('경보', 0.8284296157393211),
 ('소수', 0.8277309927452547),
 ('유권자', 0.8276739483956486),
 ('종로구', 0.8265692584129103),
 ('도전', 0.8252230481463816),
 ('코스피', 0.8206629875420192),
 ('스트레스', 0.8170898731038033),
 ('통합', 0.8162526601210984),
 ('삼성전자', 0.8116043899560662),
 ('안정적', 0.8107346141141359),
 ('등장', 0.8106657808593046),
 ('연락', 0.8102574804318825),
 ('원인', 0.8091895622757785),
 ('전북', 0.8083774264655893),
 ('중증', 0.8042479076842074),
 ('거론', 0.8022196179775811),
 ('강남', 0.8022196179775811),
 ('패션', 0.8005576940507676),
 ('무급', 0.7999031011455613),
 ('연금', 0.7995188461826414),
 ('연구진', 0.7989287088631286),
 ('대형', 0.7985912018900962),
 ('워싱턴', 0.7985047667932028),
 ('조선', 0.7968671236132328),
 ('외교', 0.7966138420081907),
 ('자산', 0.7952314966092238),
 ('대체', 0.793909145175362),
 ('기간', 0.7938704039541843),
 ('지식', 0.7938226995422579),
 ('대학', 0.7935324019405549),
 ('어린이집', 0.7930214904012833),
 ('데뷔', 0.7928258541812698),
 ('제약사', 0.7917699841507705),
 ('학교', 0.7907178414926536),
 ('항의', 0.7898229673442149),
 ('자랑', 0.7884971159488611),
 ('발송', 0.7882105631025379)]

In [52]:
w15 = word.loc[84031:92000,:] #세계일보
w15

,000만,000명,000억,10,100,1000만,1000명,100만,100명,10년,...,휴대폰,휴식,휴업,휴원,휴직,흐름,흑인,흑자,희망,희생
84031,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
84032,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
84033,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
84034,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
84035,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91996,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
91997,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
91998,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
91999,0.0,0.0,0.0,0.059292,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
92000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.048059,0.0,0.0,0.0,0.0

In [53]:
tuple = zip(w15.columns, np.max(w15.values, axis=1))
sorted_items = sorted(tuple, key = lambda x:(x[1],x[0]), reverse =True)[:70]
sorted_items

[('살포', 0.9626589603988306),
 ('데이터', 0.9246340052440536),
 ('배달', 0.9199703644355908),
 ('강화', 0.9005935704124548),
 ('이행', 0.8970781030394669),
 ('유일', 0.8855431968399217),
 ('아이', 0.8853587430180543),
 ('의존', 0.8840966931693753),
 ('손실', 0.8824051682033449),
 ('대란', 0.8789826657440736),
 ('영화관', 0.8783888235360368),
 ('중계', 0.8778494576715549),
 ('감수', 0.8764968695207623),
 ('게시', 0.8712365999555669),
 ('주문', 0.8705631687500154),
 ('차지', 0.8628625346249509),
 ('제품', 0.8532744256319187),
 ('사과', 0.8518127625827175),
 ('시점', 0.8488336125315848),
 ('금요일', 0.8435512289770883),
 ('입구', 0.8432554492869462),
 ('접촉자', 0.8406316668666478),
 ('휴대', 0.8401453185737491),
 ('속도', 0.8358917649561187),
 ('첫날', 0.8330197237080649),
 ('질병관리본부', 0.8318587346290475),
 ('개별', 0.8314353246987246),
 ('실질', 0.8296915048961926),
 ('ai', 0.8283951691616059),
 ('파악', 0.8283816021757272),
 ('면역력', 0.8276508750384898),
 ('제목', 0.8259969920284066),
 ('검증', 0.8245306251983544),
 ('가짜뉴스', 0.823642283524131),
 ('심사', 0.8230258260388508),
 ('뉴욕', 0.8226940384169922),
 ('동력', 0.8224834626104007),
 ('2020년', 0.8209030132590307),
 ('민생', 0.8207600660583957),
 ('지속적', 0.8203045755831417),
 ('진행', 0.8200922212552457),
 ('선전', 0.8198351321365424),
 ('작성', 0.8189267568325683),
 ('희생', 0.8180874184016529),
 ('배럴', 0.8169868619155507),
 ('주민', 0.8169826394878367),
 ('경기침체', 0.8147330334951656),
 ('취약', 0.8127190396694294),
 ('선포', 0.8121425200376047),
 ('60대', 0.8121026384189168),
 ('진짜', 0.8104121594971869),
 ('청와대', 0.8103350204336985),
 ('공항', 0.8099696125098541),
 ('정의', 0.8087463856035647),
 ('노래', 0.8072024914187643),
 ('안전', 0.8051614730481242),
 ('선별', 0.8047303671458639),
 ('공채', 0.8043935068781725),
 ('통화', 0.8030896077812822),
 ('자문', 0.8029309542629202),
 ('보안', 0.8023995263133641),
 ('상환', 0.8023013370409194),
 ('제안', 0.8007185361520318),
 ('군사', 0.7995474747386815),
 ('무게', 0.7980038045422041),
 ('체계', 0.7967262559511668),
 ('cj', 0.7950030447282798),
 ('추세', 0.7940986790464348),
 ('16일', 0.7924498280794194),
 ('가전', 0.7921089403884374)]

In [54]:
w16 = word.loc[92000:101623,:] #아시아경제
w16

,000만,000명,000억,10,100,1000만,1000명,100만,100명,10년,...,휴대폰,휴식,휴업,휴원,휴직,흐름,흑인,흑자,희망,희생
92000,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.048059,0.0,0.0,0.0,0.0
92001,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
92002,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
92003,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
92004,0.0,0.0,0.0,0.03998,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101619,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
101620,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
101621,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
101622,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
101623,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0

In [55]:
tuple = zip(w16.columns, np.max(w16.values, axis=1))
sorted_items = sorted(tuple, key = lambda x:(x[1],x[0]), reverse =True)[:70]
sorted_items

[('임대료', 1.0),
 ('12', 1.0),
 ('청사', 0.9306207426599434),
 ('확진자들', 0.9227130664992887),
 ('취재', 0.9026281183011414),
 ('훈련', 0.9004071230680435),
 ('위주', 0.8985056917042508),
 ('수상', 0.8936063612395607),
 ('배우', 0.8894292376779118),
 ('라이브', 0.8715852416736402),
 ('lg전자', 0.8625785289845006),
 ('대국민', 0.8503725152036109),
 ('실행', 0.8445423943464703),
 ('60', 0.8441034404288322),
 ('결국', 0.8415528868934713),
 ('누적', 0.8402044666900161),
 ('축적', 0.8342093942330401),
 ('결단', 0.8320684359991699),
 ('붕괴', 0.8307846013620905),
 ('참가', 0.8307694214122459),
 ('공천', 0.8286436562654483),
 ('특단', 0.8274569525141277),
 ('상대적', 0.8270574325161136),
 ('네이버', 0.8254758983367472),
 ('한시', 0.825245664376293),
 ('연간', 0.8248654917146039),
 ('공연', 0.8213278325767166),
 ('상상', 0.8202134584268326),
 ('국무', 0.8178261040263141),
 ('농촌', 0.8164514360942532),
 ('접속', 0.8163065621599529),
 ('태국', 0.8162070265673603),
 ('감소세', 0.8136590538789029),
 ('투입', 0.8058967231277032),
 ('요건', 0.8051923540363265),
 ('매매', 0.8037769021064529),
 ('영국', 0.7973110652177887),
 ('정책', 0.7965763626531119),
 ('진보', 0.7951646066754906),
 ('전문가', 0.7951550938821923),
 ('예방법', 0.7942011190554016),
 ('장기간', 0.7922449257593175),
 ('인물', 0.7902221790881262),
 ('법안', 0.7833614434294927),
 ('위생', 0.7831730692315767),
 ('믿음', 0.7799345543188883),
 ('물자', 0.7794582089996072),
 ('업체', 0.7786053247597963),
 ('사기', 0.7763733470616868),
 ('당정', 0.7753602495608202),
 ('입국자', 0.7737372220196279),
 ('선방', 0.7717866348224616),
 ('대면', 0.7717154754611754),
 ('의학', 0.7714385661242508),
 ('답변', 0.7696152311653448),
 ('혈장', 0.7695292087120695),
 ('의석', 0.7686684087565251),
 ('서울', 0.7686246496582024),
 ('전반적', 0.7684178161668502),
 ('주류', 0.7680827813249171),
 ('문의', 0.768051706380755),
 ('실질적', 0.7665804961686105),
 ('출국', 0.7664917334767433),
 ('10억', 0.7652106542333161),
 ('전월', 0.7612877254349631),
 ('산업', 0.7609826688590731),
 ('정원', 0.7593678187707814),
 ('ai', 0.7591484548158965),
 ('매도', 0.7589769578190991),
 ('거부', 0.7585582321692166)]

In [56]:
w17 = word.loc[101623:110669,:] #아주경제
w17

,000만,000명,000억,10,100,1000만,1000명,100만,100명,10년,...,휴대폰,휴식,휴업,휴원,휴직,흐름,흑인,흑자,희망,희생
101623,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101624,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101625,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101626,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101627,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110665,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
110666,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
110667,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
110668,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
110669,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [57]:
tuple = zip(w17.columns, np.max(w17.values, axis=1))
sorted_items = sorted(tuple, key = lambda x:(x[1],x[0]), reverse =True)[:70]
sorted_items

[('입구', 0.9181163089667672),
 ('갤럭시', 0.9121902625086324),
 ('디지털', 0.9056327233981782),
 ('성공적', 0.9045472684841078),
 ('3명', 0.9001896018193594),
 ('중앙', 0.8948533613996267),
 ('유권자들', 0.8946112270382923),
 ('걱정', 0.890579326841486),
 ('융합', 0.8868109116237822),
 ('29', 0.8852406616074757),
 ('사회', 0.8827778311274591),
 ('사실', 0.8756507350348086),
 ('전망', 0.8754285152475141),
 ('4만', 0.8711737444388873),
 ('온라', 0.8701649447518224),
 ('훼손', 0.8644897505864023),
 ('안팎', 0.8588549878192244),
 ('존중', 0.8576561352217169),
 ('발견', 0.8521681581788494),
 ('침해', 0.8513767046941321),
 ('편의점', 0.8513185705860884),
 ('주제', 0.8502509869176179),
 ('과도', 0.8493409006840288),
 ('방역', 0.8478887418789263),
 ('사상', 0.8459420719361488),
 ('인사', 0.8457498217204695),
 ('출입', 0.8444742950413412),
 ('13', 0.8436141214003134),
 ('연장', 0.8433258362253316),
 ('개시', 0.8420543514797444),
 ('진료소', 0.8387053899947695),
 ('점검', 0.8382688498459101),
 ('모색', 0.8338133513003757),
 ('국가', 0.8313977760471338),
 ('강원', 0.8294663671910373),
 ('추경안', 0.8289813076765228),
 ('대구시', 0.8289495284000356),
 ('참고', 0.827464248675893),
 ('방호복', 0.8260720624526999),
 ('물류', 0.825555078981234),
 ('입국', 0.8235351682344658),
 ('17', 0.8232646039256231),
 ('계산', 0.8231120520125741),
 ('인플루엔자', 0.8204271860085559),
 ('밀폐', 0.8200567943796115),
 ('인터넷', 0.8183924444592808),
 ('강사', 0.8183877227913261),
 ('입주', 0.8161677784103478),
 ('양성', 0.8154228122512006),
 ('심리', 0.8153920981417321),
 ('fda', 0.8153243865183509),
 ('물질', 0.8145576410606508),
 ('게시', 0.8143442670128145),
 ('주호영', 0.8117775242805859),
 ('방문자', 0.8110316566283347),
 ('본격적', 0.8108611966013697),
 ('포스트', 0.8107086801598331),
 ('입지', 0.8069551805574078),
 ('연령', 0.8065029855558867),
 ('vr', 0.8063230936346946),
 ('학교', 0.8049419824817662),
 ('공식적', 0.8046967959925527),
 ('선제', 0.8027828554450384),
 ('10', 0.8021148200682049),
 ('pcr', 0.8019903875034853),
 ('최고치', 0.8018247076635284),
 ('위로', 0.8017974908952571),
 ('고수', 0.8010264995732982),
 ('가격', 0.7977267221664925),
 ('부천', 0.794742460146459)]

In [58]:
w18 = word.loc[110669:130669,:] #조선일보
w18

,000만,000명,000억,10,100,1000만,1000명,100만,100명,10년,...,휴대폰,휴식,휴업,휴원,휴직,흐름,흑인,흑자,희망,희생
110669,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0
110670,0.0,0.0,0.0,0.083776,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0
110671,0.0,0.0,0.0,0.064063,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.09988,0.0,0.0
110672,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0
110673,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130665,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0
130666,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0
130667,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0
130668,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0
130669,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0

In [59]:
tuple = zip(w18.columns, np.max(w18.values, axis=1))
sorted_items = sorted(tuple, key = lambda x:(x[1],x[0]), reverse =True)[:70]
sorted_items

[('보통', 0.9354669778678192),
 ('거짓말', 0.9346384299857854),
 ('입항', 0.9223981519082411),
 ('패션', 0.9151074202257196),
 ('철저', 0.9069606591401854),
 ('연설', 0.9058936849643128),
 ('부진', 0.8896809619211636),
 ('3개', 0.8877596072669801),
 ('출시', 0.8831610718161528),
 ('영업이익', 0.8811913182588783),
 ('투표소', 0.8808573094652459),
 ('부처', 0.8772435952554479),
 ('파장', 0.8746742301446893),
 ('내각', 0.8702222033046239),
 ('총재', 0.866499589590402),
 ('마켓', 0.8649338045235695),
 ('주자', 0.8627132320930452),
 ('이외', 0.8602284715255736),
 ('영역', 0.858380658202481),
 ('위원장', 0.8519413454181319),
 ('pc방', 0.8511766302293887),
 ('모금', 0.8508425942926945),
 ('부본부장', 0.8498399476022351),
 ('매매', 0.8387262683038097),
 ('하원', 0.8383588006955486),
 ('목적', 0.8339399540277029),
 ('아버지', 0.8328004880216062),
 ('연일', 0.8309972179911518),
 ('테슬라', 0.8299516455403307),
 ('매입', 0.8295072463626462),
 ('며칠', 0.8283933884946769),
 ('수익성', 0.8274304478303454),
 ('생계', 0.8263375142544709),
 ('뉴욕', 0.8247969365509829),
 ('탄생', 0.8247637202062328),
 ('개방', 0.8215601295797189),
 ('가짜뉴스', 0.8210248359162644),
 ('박능후', 0.8208769057440272),
 ('파우치', 0.8198064686412059),
 ('전일', 0.8189569929317049),
 ('민생', 0.8156039844675899),
 ('학기', 0.8137011083819875),
 ('공격', 0.8109723787978022),
 ('보고', 0.8105837728172494),
 ('사고', 0.8072256320391243),
 ('인물', 0.807025571230286),
 ('카페', 0.8067726268976905),
 ('비상', 0.8059936501115971),
 ('대유행', 0.8057891980624302),
 ('세트', 0.8054402462231105),
 ('국내총생산', 0.8049460075467175),
 ('9명', 0.8001741120470024),
 ('국제', 0.7989266813022391),
 ('순차적', 0.7971918470660628),
 ('어려움', 0.7964925194771593),
 ('고심', 0.796428699010583),
 ('성적', 0.796372399274487),
 ('은행', 0.7963357662301915),
 ('통합', 0.7961702629364059),
 ('소송', 0.7944805812928469),
 ('야당', 0.7941242733329391),
 ('회원', 0.7921039767835485),
 ('실내', 0.7915848755711307),
 ('증명', 0.7896595489362258),
 ('4년', 0.7893064014040931),
 ('재개', 0.7890888527520145),
 ('세종', 0.7887516129720004),
 ('북한', 0.7854588021045216),
 ('5월', 0.7854112995599515),
 ('경찰', 0.7852649292125553)]

In [61]:
w19 = word.loc[130669:142858,:] #중앙일보
w19

,000만,000명,000억,10,100,1000만,1000명,100만,100명,10년,...,휴대폰,휴식,휴업,휴원,휴직,흐름,흑인,흑자,희망,희생
130669,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0
130670,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0
130671,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0
130672,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0
130673,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.198248,0.000000,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.085123,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142854,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.050047,0.000000,0.0
142855,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0
142856,0.0,0.0,0.0,0.0,0.0,0.0,0.076462,0.000000,0.143571,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0
142857,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0
142858,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.029139,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0

In [62]:
tuple = zip(w19.columns, np.max(w19.values, axis=1))
sorted_items = sorted(tuple, key = lambda x:(x[1],x[0]), reverse =True)[:70]
sorted_items

[('일대', 0.9144030335281732),
 ('민족', 0.9144030335281732),
 ('mbc', 0.9090862368835132),
 ('여자', 0.9023078604049641),
 ('만기', 0.9023078604049641),
 ('동일', 0.9023078604049641),
 ('단행', 0.9023078604049641),
 ('기소', 0.9023078604049641),
 ('pc', 0.9023078604049641),
 ('존중', 0.9001484051040248),
 ('눈물', 0.8907527872481157),
 ('전자', 0.8892474010554637),
 ('해소', 0.8892422206479496),
 ('현실', 0.8865890330623923),
 ('국난', 0.8865247858886848),
 ('부탁', 0.882729363570703),
 ('협업', 0.8793358491961423),
 ('장병', 0.8735897802109461),
 ('현실적', 0.8720500205799885),
 ('생중계', 0.8671214146587745),
 ('승무원', 0.8666931244498881),
 ('전염병', 0.8665186850110124),
 ('헬스', 0.8649333795312224),
 ('징역', 0.8646484858859641),
 ('방지', 0.8624155443432425),
 ('중순', 0.8622250710488354),
 ('전월', 0.8580415212387441),
 ('항공기', 0.8579117603919441),
 ('방문', 0.8576788969949153),
 ('존슨', 0.8572246821154474),
 ('고생', 0.8513216284905831),
 ('눈치', 0.8494390089399791),
 ('협치', 0.8474592143554323),
 ('8만', 0.8456853219776007),
 ('경기침체', 0.8453854383321463),
 ('관내', 0.8403307373950731),
 ('60대', 0.8351237129733986),
 ('후보자', 0.8334874954900271),
 ('확률', 0.8321543209943155),
 ('가능성', 0.8315410539435855),
 ('상상', 0.8308901494300396),
 ('둔화', 0.830840341497675),
 ('정당', 0.8307593003752556),
 ('여건', 0.8283890040940147),
 ('환영', 0.8279097591332597),
 ('매장', 0.8271254425484725),
 ('본부', 0.8262439191956256),
 ('필수', 0.8262374672969918),
 ('선제', 0.8246217084097668),
 ('기간', 0.8240791260865261),
 ('표준', 0.8225266927284324),
 ('지침', 0.8212144383093666),
 ('한편', 0.8195570645278397),
 ('종교', 0.8190267671793643),
 ('향상', 0.8184841508896534),
 ('비즈니스', 0.8180079658529098),
 ('34', 0.8173689282857745),
 ('분들', 0.8168014791754651),
 ('주목', 0.8158009221047591),
 ('지하', 0.8155750878193437),
 ('감당', 0.8154554276319165),
 ('플러스', 0.8153566120982582),
 ('상향', 0.8148348524101582),
 ('영어', 0.8146740403790216),
 ('작가', 0.8145154363302305),
 ('공포', 0.8138071671305992),
 ('삭감', 0.8136561754035224),
 ('집단', 0.8116909121706565),
 ('전반적', 0.8110327744856701),
 ('추구', 0.8109347043004425)]

In [63]:
w20 = word.loc[142858:146543,:] #파이낸셜뉴스
w20

,000만,000명,000억,10,100,1000만,1000명,100만,100명,10년,...,휴대폰,휴식,휴업,휴원,휴직,흐름,흑인,흑자,희망,희생
142858,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.029139,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
142859,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.058082,0.0,0.0,0.000000,0.0
142860,0.0,0.0,0.0,0.000000,0.057424,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
142861,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
142862,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146539,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
146540,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.058108,0.0
146541,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
146542,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
146543,0.0,0.0,0.0,0.085502,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0

In [64]:
tuple = zip(w20.columns, np.max(w20.values, axis=1))
sorted_items = sorted(tuple, key = lambda x:(x[1],x[0]), reverse =True)[:70]
sorted_items

[('주간', 0.9425407989099428),
 ('크루즈', 0.9256964261407457),
 ('아세안', 0.9114132608935912),
 ('뉴시스', 0.9094426654349456),
 ('한미', 0.9080584810080286),
 ('설립', 0.9029264454653442),
 ('기자들', 0.8731884380531825),
 ('요소', 0.8730595831956469),
 ('확진환자', 0.8681557086155458),
 ('탄핵', 0.8603943743795435),
 ('전력', 0.8574931040247841),
 ('박사', 0.8548827896160477),
 ('브라질', 0.8514835938199845),
 ('수상', 0.8490079007686658),
 ('정신', 0.848597702627146),
 ('일반적', 0.8460694546282692),
 ('스루', 0.8453197964377139),
 ('차지', 0.8399259660792765),
 ('5년', 0.8374115520532914),
 ('도서관', 0.833999754845971),
 ('원내', 0.8329362872038198),
 ('롯데백화점', 0.8313166747792063),
 ('증거', 0.8272306557236058),
 ('진원지', 0.827163057232015),
 ('매수', 0.8255082721973487),
 ('sk', 0.8254501565526169),
 ('연말', 0.8235458820992076),
 ('면적', 0.8234251004009671),
 ('전수조사', 0.8234075796735317),
 ('헌신', 0.8233110325263809),
 ('채용', 0.8226115218157818),
 ('공기', 0.8209351994432704),
 ('아산', 0.8200564951939371),
 ('사정', 0.8175947093802438),
 ('교민들', 0.8168655068562727),
 ('실제', 0.8158308862964592),
 ('능력', 0.8155074237735794),
 ('양산', 0.8154282051595696),
 ('일주일', 0.8128203086408505),
 ('시범', 0.8120443458504795),
 ('감소', 0.8114394988719794),
 ('출범', 0.8111693894266453),
 ('부동산', 0.8105956481208609),
 ('위험성', 0.8098228965142464),
 ('위험', 0.8098228965142464),
 ('33', 0.8038632026871154),
 ('nyt', 0.8036501953180866),
 ('기초', 0.8000422581252893),
 ('대사관', 0.7995878716138081),
 ('확진판정', 0.7981661881427895),
 ('영역', 0.7963716103239527),
 ('상태', 0.7961142497212954),
 ('인도', 0.7955440267559454),
 ('인프라', 0.7946317633110304),
 ('공중', 0.7945266344495091),
 ('체육', 0.7940298327492658),
 ('심사', 0.7930164385897396),
 ('체계', 0.7928362024488598),
 ('명품', 0.7926659327694591),
 ('국제통화기금', 0.7922685001693753),
 ('완화', 0.7906601077499456),
 ('용품', 0.7904066088408968),
 ('정례', 0.790361169566822),
 ('환영', 0.7881365054555813),
 ('발행', 0.7873585437645159),
 ('의류', 0.784311883966162),
 ('해수욕장', 0.7834431429892744),
 ('갤럭시', 0.7833539675990728),
 ('가능성', 0.7828284206938056),
 ('긍정', 0.7821510699829691)]

In [65]:
w21 = word.loc[146543:149196,:] #한겨레
w21

,000만,000명,000억,10,100,1000만,1000명,100만,100명,10년,...,휴대폰,휴식,휴업,휴원,휴직,흐름,흑인,흑자,희망,희생
146543,0.0,0.0,0.0,0.085502,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
146544,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
146545,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
146546,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
146547,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149192,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
149193,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
149194,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
149195,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
149196,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.121622,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [66]:
tuple = zip(w21.columns, np.max(w21.values, axis=1))
sorted_items = sorted(tuple, key = lambda x:(x[1],x[0]), reverse =True)[:70]
sorted_items

[('유포', 0.9330898240673532),
 ('월요일', 0.9317771271531656),
 ('의료', 0.931667268108902),
 ('부천', 0.9143468421989096),
 ('추세', 0.9143191991625896),
 ('동결', 0.8940815488742224),
 ('객실', 0.8879786040018627),
 ('물자', 0.8876093475945379),
 ('1위', 0.8808595254305431),
 ('디스플레이', 0.8743545427250049),
 ('이야기', 0.8740262016909781),
 ('측정', 0.8738463412366183),
 ('무대', 0.8673661502357355),
 ('거점', 0.8663307428803567),
 ('80', 0.8662369609093715),
 ('10', 0.862547917490684),
 ('여론', 0.8596949318236063),
 ('발견', 0.857057880212629),
 ('장비', 0.8567504827796809),
 ('오피스', 0.8514174540312646),
 ('47', 0.8497778624301726),
 ('중단', 0.8463843006822924),
 ('국내총생산', 0.8459661888458141),
 ('라디오', 0.8439460875503295),
 ('이외', 0.8401828782272568),
 ('독감', 0.8389726919744299),
 ('선수', 0.8375978695444826),
 ('이태원', 0.8371342512138745),
 ('김정은', 0.8359139603416834),
 ('주식', 0.8325281918639749),
 ('설정', 0.8317459851105933),
 ('주년', 0.8314848636256739),
 ('게재', 0.8312274565582841),
 ('책임자', 0.8290306051040153),
 ('중국', 0.8276945337324445),
 ('10년', 0.8257800591599511),
 ('임상시험', 0.8225581744701984),
 ('코로', 0.8224438278989614),
 ('순위', 0.8223238285016335),
 ('이사회', 0.8202225900551183),
 ('캡처', 0.8180349215025724),
 ('의협', 0.8175727644097949),
 ('출근', 0.8156813267835338),
 ('기조', 0.8145217417642819),
 ('자치', 0.8137104551828537),
 ('의혹', 0.8131594373737219),
 ('참가', 0.8115958023803094),
 ('최저', 0.8114143096236682),
 ('가속화', 0.8101418828607561),
 ('유입', 0.8099934546876096),
 ('주말', 0.8097680601261308),
 ('안정적', 0.807391533773534),
 ('시범', 0.8061730738656204),
 ('논쟁', 0.8060259621360949),
 ('의원', 0.8052024757747851),
 ('설명', 0.8030033642907759),
 ('귀국', 0.8020268626601423),
 ('접종', 0.8007817964285913),
 ('신용', 0.8005920270035155),
 ('청사', 0.7997079506427696),
 ('관계자', 0.7976635320351729),
 ('광주', 0.7973047439463704),
 ('주요국', 0.7951643263277641),
 ('인공', 0.7917411059146502),
 ('본회의', 0.7913753320544252),
 ('7월', 0.7904323772678513),
 ('3월', 0.7871602754414109),
 ('금액', 0.7871220836729526),
 ('시민들', 0.7832419616474794),
 ('입학', 0.7830302593132838)]

In [67]:
w22 = word.loc[149196:159109,:] #한국경제
w22

,000만,000명,000억,10,100,1000만,1000명,100만,100명,10년,...,휴대폰,휴식,휴업,휴원,휴직,흐름,흑인,흑자,희망,희생
149196,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.121622,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
149197,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
149198,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
149199,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
149200,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.080257,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159105,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
159106,0.0,0.0,0.0,0.073516,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
159107,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
159108,0.0,0.0,0.0,0.150901,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
159109,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0

In [68]:
tuple = zip(w22.columns, np.max(w22.values, axis=1))
sorted_items = sorted(tuple, key = lambda x:(x[1],x[0]), reverse =True)[:70]
sorted_items

[('중계', 1.0),
 ('검출', 0.9243098036089084),
 ('생중계', 0.9231656235286329),
 ('외국인', 0.9229870850679722),
 ('비상', 0.9201003298389724),
 ('유일', 0.9082607621772636),
 ('재편', 0.9077618827693535),
 ('pcr', 0.9056579273675408),
 ('정리', 0.9015767237055812),
 ('용기', 0.9000000042539223),
 ('재난지원금', 0.8892417775174227),
 ('고향', 0.8856398141452201),
 ('구분', 0.8833846329641732),
 ('움직임', 0.8815701618529336),
 ('해외여행', 0.8780564277521506),
 ('3단계', 0.8760830249265918),
 ('안전성', 0.8746810255647061),
 ('재난', 0.8641384741442896),
 ('전자', 0.8560682875320289),
 ('안전망', 0.8477327894953594),
 ('나라들', 0.8427941519500064),
 ('21일', 0.8399134829112811),
 ('침체', 0.8396269359204472),
 ('도쿄도', 0.8392895679527531),
 ('노동', 0.8329253898744694),
 ('임시', 0.8324808713388009),
 ('대한민국', 0.8323742798396057),
 ('회복세', 0.8323326952910666),
 ('물품', 0.8299955244148655),
 ('휴식', 0.8297494048257908),
 ('48', 0.8274147750364954),
 ('이탈리아', 0.8258757118813397),
 ('컨설팅', 0.8251770464670909),
 ('단어', 0.8247936340757214),
 ('말레이시아', 0.8244014843709306),
 ('대국민', 0.8241363093394402),
 ('이외', 0.8238485825168617),
 ('3분', 0.8218621100803811),
 ('구역', 0.8177527025941695),
 ('상징', 0.8162483916817521),
 ('주최', 0.8162144949470642),
 ('방식', 0.814492187451362),
 ('마지막', 0.8131340339423467),
 ('세기', 0.8129598493299142),
 ('기자들', 0.8095111582496914),
 ('차단', 0.8077737335222025),
 ('주주', 0.8074473655300319),
 ('2월', 0.8065589377143298),
 ('베이징', 0.8050775942148637),
 ('이태원', 0.8046197078558099),
 ('정상', 0.8040430202171595),
 ('경남', 0.8017327246785928),
 ('중구', 0.8010402092812279),
 ('택배', 0.8005141029856573),
 ('주장', 0.7975288820799021),
 ('품목', 0.7947374698271992),
 ('초유', 0.7927512161536888),
 ('세종', 0.7913826410277359),
 ('로봇', 0.7900677658903488),
 ('수출액', 0.7898899295300076),
 ('가속화', 0.7898017110335898),
 ('공정', 0.7892831374088112),
 ('실현', 0.7887812108355337),
 ('공천', 0.7885398008935712),
 ('사회적', 0.7884705371323595),
 ('체제', 0.7882214003454604),
 ('현지', 0.7875246711120972),
 ('8월', 0.7873375278226752),
 ('문재인', 0.7866217642409196),
 ('클라우드', 0.7858587439310767)]

In [69]:
w23 = word.loc[159109:168681,:] #한국일보
w23

,000만,000명,000억,10,100,1000만,1000명,100만,100명,10년,...,휴대폰,휴식,휴업,휴원,휴직,흐름,흑인,흑자,희망,희생
159109,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
159110,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
159111,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
159112,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
159113,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168677,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
168678,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
168679,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
168680,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
168681,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [70]:
tuple = zip(w23.columns, np.max(w23.values, axis=1))
sorted_items = sorted(tuple, key = lambda x:(x[1],x[0]), reverse =True)[:70]
sorted_items

[('현장', 0.9550759104957192),
 ('상시', 0.9309942497979784),
 ('응급실', 0.927143231510109),
 ('기본', 0.8961909572512845),
 ('존경', 0.8958798463150867),
 ('대면', 0.8892624659902767),
 ('인력', 0.8828083291834152),
 ('기본소득', 0.8795758984253336),
 ('삼성전자', 0.8730615985599262),
 ('긍정', 0.8613229153392468),
 ('승무원', 0.8534121724646083),
 ('가동', 0.8523594232238733),
 ('수행', 0.8464647820579038),
 ('강조', 0.8444541760056381),
 ('19일', 0.8435339243199712),
 ('전북', 0.8422023695919626),
 ('개정안', 0.8416863026367539),
 ('귀국', 0.8395908413551519),
 ('5g', 0.8393124597672021),
 ('센터', 0.838057555531306),
 ('일종', 0.8372625585312905),
 ('공연', 0.8365003219547174),
 ('투입', 0.8349835188882944),
 ('기관', 0.8309477373014104),
 ('감산', 0.8306433688634229),
 ('22일', 0.8298946813627516),
 ('본부장', 0.8277728332536846),
 ('추가적', 0.8275294717900334),
 ('지도자', 0.8263493431776435),
 ('예년', 0.826095486123549),
 ('전당', 0.8240221028951891),
 ('주력', 0.8219317609795391),
 ('사망률', 0.8210935826098064),
 ('실효성', 0.8193904337937197),
 ('정도', 0.8190419676649309),
 ('관광지', 0.8156958009393365),
 ('lg', 0.8061033469163056),
 ('외국인', 0.8060768771742309),
 ('여의도', 0.8028813517350183),
 ('개입', 0.8025598996924812),
 ('대기', 0.8000088170060954),
 ('발동', 0.7997005024124592),
 ('연구팀', 0.7995133397499182),
 ('보장', 0.7982743849301848),
 ('감염원', 0.7982137437478412),
 ('양보', 0.7981955864452017),
 ('업무', 0.7980414743872517),
 ('반박', 0.7979469937573606),
 ('돌파', 0.7972400835855148),
 ('실질', 0.7967010625694972),
 ('제외', 0.7914679489519971),
 ('교사', 0.7903519701847079),
 ('충격', 0.789109709309135),
 ('수업', 0.7868622427408569),
 ('가전', 0.7850682785420685),
 ('가슴', 0.7849128773416473),
 ('매출', 0.7846105648200344),
 ('재택', 0.7844075939939155),
 ('4개월', 0.7841358940424337),
 ('매매', 0.783473550733936),
 ('인구', 0.7833709854669566),
 ('아프리카', 0.7828100297717997),
 ('정식', 0.7823672156401008),
 ('항체', 0.7822352086834897),
 ('행정안전부', 0.7819726531804123),
 ('취약계층', 0.7808562860997094),
 ('출범', 0.7804643569582828),
 ('어려움', 0.7803647553946961),
 ('구분', 0.7791872047186136),
 ('재난지원금', 0.7789235280595582)]

In [71]:
w24 = word.loc[168681:178617,:] #헤럴드경제
w24

,000만,000명,000억,10,100,1000만,1000명,100만,100명,10년,...,휴대폰,휴식,휴업,휴원,휴직,흐름,흑인,흑자,희망,희생
168681,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
168682,0.0,0.0,0.0,0.039171,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
168683,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
168684,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
168685,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178609,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
178610,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
178611,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
178612,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
178613,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [72]:
tuple = zip(w24.columns, np.max(w24.values, axis=1))
sorted_items = sorted(tuple, key = lambda x:(x[1],x[0]), reverse =True)[:70]
sorted_items

[('성장률', 0.9339562330532379),
 ('팀장', 0.9201156458442966),
 ('일반적', 0.916332516169073),
 ('이송', 0.91612293574726),
 ('체포', 0.9062340001809088),
 ('기자들', 0.8970810068579304),
 ('졸업', 0.8932301582871534),
 ('편의점', 0.8842595367510222),
 ('동행', 0.8819313133185038),
 ('기타', 0.880506725384605),
 ('비용', 0.8755804198637908),
 ('공식', 0.8722270585539567),
 ('개원', 0.8703359151262524),
 ('캠프', 0.8695738504472416),
 ('압박', 0.85390573804995),
 ('상황', 0.8516929279958829),
 ('규모', 0.8504111992717602),
 ('lg화학', 0.8498785631482609),
 ('그룹', 0.8490742685396101),
 ('현장', 0.8489023479845198),
 ('고개', 0.8488976315469978),
 ('착용', 0.848534808000041),
 ('현실적', 0.8483863606250998),
 ('출입', 0.8481438113281023),
 ('시즌', 0.8465742907813526),
 ('치명률', 0.8435069116069557),
 ('위원장', 0.8426778940330082),
 ('폭락', 0.8422283020553193),
 ('순간', 0.8409585560023275),
 ('시국', 0.8341587738257601),
 ('설문', 0.8338902720202915),
 ('백악관', 0.8311797880759452),
 ('법안', 0.8292229571119375),
 ('24', 0.8288828657289176),
 ('고심', 0.825065192552583),
 ('경보', 0.825065192552583),
 ('물류', 0.822767485030127),
 ('공유', 0.8225773532881687),
 ('신임', 0.8156120703158813),
 ('총액', 0.8131699650217636),
 ('근처', 0.8124544397850685),
 ('여파', 0.8118382772498531),
 ('사업자', 0.8116853334855664),
 ('부품', 0.8111502909888063),
 ('파견', 0.8104994265567496),
 ('대리점', 0.8104083643392097),
 ('1분기', 0.8093608536813717),
 ('스페인', 0.8084887134078325),
 ('10일', 0.8082117054344315),
 ('폭증', 0.8071335282074055),
 ('건물', 0.8071330339228143),
 ('쿠폰', 0.8069904601899108),
 ('이틀', 0.8069128361260084),
 ('회계', 0.8068428908254989),
 ('모바일', 0.8067061228330691),
 ('포럼', 0.804257520894967),
 ('표준', 0.8032072228168825),
 ('재정부', 0.8023950190964309),
 ('보험', 0.8014065537941307),
 ('신청자', 0.8013274786159739),
 ('성금', 0.8012264152284864),
 ('채널', 0.8012114948722743),
 ('구체적', 0.7993517231490225),
 ('자제', 0.7989518212009615),
 ('삭감', 0.7985826025270094),
 ('측면', 0.798552938303499),
 ('동반', 0.7981060335768665),
 ('잠복기', 0.7977510650339397),
 ('귀가', 0.7974454736230142),
 ('지도부', 0.7946953358442631)]